---
title: "funding"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{funding}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(USF)
library(dplyr)
library(tidyverse)
library(kableExtra)
```

## Baltimore NIJ Example

### Information on grantees

```{r include=FALSE}
# load data
data("more_nijgrants")
```

### Solicitors

```{r}
#knitr::kable(more_nijgrants %>% group_by(Solicitor) %>% count() %>% arrange(-n))
```


### Entity awarded the most amount of grants: City of Baltimore/City

```{r echo=FALSE}
knitr::kable(more_nijgrants %>% group_by(Recipient) %>% count() %>% arrange(-n)) 
```

#### Projects funded: crime lab/forensics/DNA backlog
```{r}
knitr::kable(more_nijgrants %>% filter(Recipient == "Baltimore City") %>% 
  select("Title"))
knitr::kable(more_nijgrants %>% filter(Recipient == "City of Baltimore") %>% 
  select("Title"))
```

#### Year of awards: 1999 to 2013, who is funding them now?

```{r}
knitr::kable(more_nijgrants %>% filter(Recipient == "Baltimore City") %>% 
               select("Fiscal_Y"))
knitr::kable(more_nijgrants %>% filter(Recipient == "City of Baltimore") %>% 
               select("Fiscal_Y"))
```

How much?

```{r eval=FALSE, include=FALSE}
more_nijgrants %>% filter(Recipient == "Baltimore City") %>% 
  select("Amount") %>% sum(.)
more_nijgrants %>% filter(Recipient == "City of Baltimore") %>% 
  select("Amount") %>% sum(.)
```

#### Total amounts awarded: $6,135,138 from 1999 to 2013
```{r}
t1 <- 507895
t2 <- 5627243
total <- t1 + t2
#total = 6135138
```

### Ranked #2 as most funded: Baltimore County Maryland 

```{r}
knitr::kable(more_nijgrants %>% filter(Recipient == "Baltimore County Maryland") %>% 
  select("Title"))
```



### General search on risk or policing

```{r}
knitr::kable(more_nijgrants %>% 
  filter( grepl("Risk", Title) | 
            grepl("Police", Title) | 
    grepl("Violence", Title) | 
  grepl("Weapons", Title)))
```
