---
title: "Test for Chicago"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Test for Chicago}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(USF)
```

# Crime map
```{r}
setwd("~/Clark/RA-ing/SummerInstitute/GIS")
crime_map <- read.csv("~/Clark/RA-ing/SummerInstitute/GIS/chicago/Crimes_-_Map.csv")
crime_map$LATITUDE[is.na(crime_map$LATITUDE)] <- 0
crime_map$LONGITUDE[is.na(crime_map$LONGITUDE)] <- 0

crime_map_sf <- st_as_sf(crime_map, 
                            coords = c("LONGITUDE", "LATITUDE"), crs = 4269)
plot(crime_map_sf$geometry)
```

# Zoning
```{r}
setwd("~/Clark/RA-ing/SummerInstitute/GIS")
zoning_ch <- st_read("~/Clark/RA-ing/SummerInstitute/GIS/chicago/Boundaries - Zoning Districts (current)/geo_export_20e190ae-72ff-4361-b6b2-9af7a94a96db.shp")
```

# Assessor's data
```{r}
ch_ass_data <- read.csv("~/Clark/RA-ing/SummerInstitute/GIS/chicago/Cook_County_Assessor_s_Residential_Property_Characteristics.csv")

ch_ass_data$Latitude[is.na(ch_ass_data$Latitude)] <- 0
ch_ass_data$Longitude[is.na(ch_ass_data$Longitude)] <- 0
ch_ass_data_sf <- st_as_sf(ch_ass_data, 
                            coords = c("Longitude", "Latitude"), crs = 4269)
plot(ch_ass_data_sf$geometry)
plot(zoning_ch$geometry, add = TRUE)
```

Wards crimes
```{r}
ch_crimes <- read.csv("~/Clark/RA-ing/SummerInstitute/GIS/chicago/Crimes_-_Map.csv")

ch_crimes <- ch_crimes %>% group_by(WARD) %>% count()

write.csv(ch_crimes,
          file = "~/Clark/RA-ing/SummerInstitute/USF/inst/data/ch_crimes_sum.csv")
```


