---
title: "san_francisco"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{san_francisco}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(USF)
library(sf)
library(tidyverse)
library(tmap)
library(ggplot2)
```

----

New data: Secured Property Tax Data from 2007/08 to 2020/21 tax year 
[Source](https://www.sfassessor.org/news-information/property-data-0)

```{r}
# read excel sheets
library(here)
library(readxl)

# read excel_sheet
excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2007-2008.xlsx"))

# specify worksheet 1 "Roll Data 2007-2008"

# ptaxdata_0708 <- read_excel(
#   here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2007-2008.xlsx"), 
#   sheet = "Roll Data 2007-2008") %>% .[-c(1, 2, 4:18)] 
# 
# ptaxdata_0708[1] <-ptaxdata_0708[1] %>% 
#   mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))


# 2008-09
excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2008-2009.xlsx"))

ptaxdata_0809 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2008-2009.xlsx"), 
  sheet = "Roll Data 2008-2009") %>% .[-c(1, 2, 4:18)]

ptaxdata_0809[1] <-ptaxdata_0809[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2009-10
# read excel_sheet
excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2009-2010.xlsx"))

ptaxdata_0910 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2009-2010.xlsx"), 
  sheet = "2009-2010") %>% .[-c(1, 2, 4:18)]

ptaxdata_0910[1] <-ptaxdata_0910[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2010-11
excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2010-2011.xlsx"))

ptaxdata_1011 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2010-2011.xlsx"), 
  sheet = "Roll Data 2010-2011") %>% .[-c(1, 2, 4:18)]

ptaxdata_1011[1] <-ptaxdata_1011[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2011-12

excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.11.5__SF_ASR_Secured_Roll_Data_2011-2012.xlsx"))

ptaxdata_1112 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.11.5__SF_ASR_Secured_Roll_Data_2011-2012.xlsx"), 
  sheet = "Roll Data 2011-2012") %>% .[-c(1, 2, 4:18)]

ptaxdata_1112[1] <-ptaxdata_1112[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))


# 2012-13

ptaxdata_1213 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2012-2013.xlsx"),
  sheet = "Roll Data 2012-2013") %>% .[-c(1, 2, 4:18)]

ptaxdata_1213[1] <-ptaxdata_1213[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2013-14

excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2013-2014.xlsx"))

ptaxdata_1314 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2013-2014.xlsx"), 
  sheet = "Roll Data 2013-2014") %>% .[-c(1, 2, 4:18)]

ptaxdata_1314[1] <-ptaxdata_1314[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2014-15
excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2014-2015.xlsx"))

ptaxdata_1415 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.20__SF_ASR_Secured_Roll_Data_2014-2015.xlsx"), 
  sheet = "2014-2015") %>% .[-c(1, 2, 4:23)]

ptaxdata_1415[1] <-ptaxdata_1415[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2015-16

excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2020.7.10_SF_ASR_Secured_Roll_Data_2015-2016.xlsx"))

ptaxdata_1516 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2020.7.10_SF_ASR_Secured_Roll_Data_2015-2016.xlsx"), 
  sheet = "Roll Data 2015-2016") %>% .[-c(1, 2, 4:18)]

ptaxdata_1516[1] <-ptaxdata_1516[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2016-17

excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.12__SF_ASR_Secured_Roll_Data_2016-2017_0.xlsx"))

ptaxdata_1617 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.12__SF_ASR_Secured_Roll_Data_2016-2017_0.xlsx"), 
  sheet = "Roll Data 2016-2017") %>% .[-c(1, 2, 4:18)]

ptaxdata_1617[1] <-ptaxdata_1617[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2017-18

ptaxdata_1718 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2019.8.12__SF_ASR_Secured_Roll_Data_2017-2018.xlsx"),
                          sheet = "Roll Data 2017-2018")%>% .[-c(1, 2, 4:18)]

ptaxdata_1718[1] <-ptaxdata_1718[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))


# 2018-19

excel_sheets(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2020.7.10_SF_ASR_Secured_Roll_Data_2018-2019.xlsx"))

ptaxdata_1819 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2020.7.10_SF_ASR_Secured_Roll_Data_2018-2019.xlsx"), 
  sheet = "Roll Data 2018-2019") %>% .[-c(1, 3:18)]

ptaxdata_1819[1] <-ptaxdata_1819[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2019-20

ptaxdata_1920 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2020.7.10_SF_ASR_Secured_Roll_Data_2019-2020.xlsx"),
                          sheet = "Roll Data 2019-2020") %>% .[-c(1, 3:18)]

ptaxdata_1920[1] <-ptaxdata_1920[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))

# 2020-21

ptaxdata_2021 <- read_excel(
  here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/assessors/2021.7.28_SF_ASR_Secured_Roll_Data_2020-2021.xlsx"),
                          sheet = "Roll Data 2020-2021") %>% .[-c(1, 3:18)]

ptaxdata_2021[1] <-ptaxdata_2021[1] %>% 
  mutate(across(where(is.character), str_remove_all, pattern = fixed(" ")))


```

Police districts

```{r}
library(here)
sf_pdistricts <- st_read(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/Current Police Districts/geo_export_9bf54163-ba35-4dfa-953f-b7357987d6f9.shp"))
```

Land use

```{r}
library(here)
sf_landuse <- st_read(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/Land Use/geo_export_bfa75090-fc16-491b-939a-36adb7e3dbdf.shp"))
```



Parcel data

```{r}
parcels <- st_read("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/Parcels/Parcels/sanfranparcel.shp")

# change name to match `ptdata_XXXX`

names(parcels)[1] <- "RP1PRCLID"

# attempt join

sf_0708 <- right_join(parcels, ptaxdata_0708, by = "RP1PRCLID") %>% st_as_sf()

sf_1213 <- right_join(parcels, ptaxdata_1213, by = "RP1PRCLID") %>% st_as_sf()

sf_1718 <- right_join(parcels, ptaxdata_1718, by = "RP1PRCLID") %>% st_as_sf()

sf_1920 <- right_join(parcels, ptaxdata_1920, by = "RP1PRCLID") %>% st_as_sf() 

sf_2021 <- right_join(parcels, ptaxdata_2021, by = "RP1PRCLID") %>% st_as_sf() 


```

Map? Works with `ggplot` but doesn't with `tmap` - need to fix bugs


```{r}

# quantile(ptaxdata_0708$RP1LNDVAL)
# sf0708_breaks <- c(1, 36370, 140186, 1475439, 256020000)

sd(ptaxdata_0708$RP1LNDVAL)


sf_1920 %>%
  ggplot(aes(fill = RP1LNDVAL)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma", na.value = "light grey",
                       breaks = sf0708_breaks) +
  labs(title = "Assessed value of land 07/08")
```

Export `.SHP` for ArcOnline hosting

```{r}
# write SHP

#st_write(sf_0708, 
#         "~/Clark/RA-ing/SummerInstitute/USF/localdrive/sf_0708.shp", 
#         driver = "ESRI Shapefile")

# st_write(sf_1213,
#         "~/Clark/RA-ing/SummerInstitute/USF/localdrive/sf_1213.shp",
#         driver = "ESRI Shapefile")
# 
# st_write(sf_1718,
#         "~/Clark/RA-ing/SummerInstitute/USF/localdrive/sf_1718.shp",
#         driver = "ESRI Shapefile")
# 
# st_write(sf_1920,
#         "~/Clark/RA-ing/SummerInstitute/USF/localdrive/sf_1920.shp",
#         driver = "ESRI Shapefile")
# 
# st_write(sf_2021,
#         "~/Clark/RA-ing/SummerInstitute/USF/localdrive/sf_2021.shp",
#         driver = "ESRI Shapefile")

```

-----

Calls service - need address locator

```{r}
sf_pdcalls <- st_read("~/Clark/RA-ing/SummerInstitute/USF/localdrive/sf_pdcalls.shp")
```

Police department incident report
```{r}
library(here)
library(sp)
sf_incident <- st_read(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/Police Department Incident Reports_ 2018 to Present/geo_export_4f55bd45-1b85-4d17-955a-73a401af9732.shp"))
```

Misconduct
```{r}
library(here)
CopMonitor <- read.csv(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/CopMonitor Public Records.csv"))
names(CopMonitor)[1] <- "Name"

CopMonitor$Officer.Agency %>% unique()
```

Police budget
```{r}
sf_pdbudget <- read.csv("~/Clark/RA-ing/SummerInstitute/budget/sf_policebudget.csv")
sf_pdstaff2007 <- read.csv("~/Clark/RA-ing/SummerInstitute/budget/sf_policestaffing2007.csv")
sf_fedgrants <- read.csv(here("~/Clark/RA-ing/SummerInstitute/GIS/sanfran/sf_fedgrants.csv"))
```

